version: "3.8"
services:
  db:
    image: "postgres:13.0-alpine"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=informbob
      - POSTGRES_USER=informbob-db-admin
      - POSTGRES_PASSWORD=super-secure-babula
    expose:
       - "5432"
    volumes:
      - ./prod/db/data:/var/lib/postgresql/data
    networks:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 200M
  app:
    image: ghcr.io/pronto-ag/pronto-mia-server:v0.1.0
    restart: unless-stopped
    volumes:
      - ./prod/app/config/appsettings.json:/app/appsettings.json
      - ./prod/app/config/appsettings.Production.json:/app/appsettings.Production.json
      - ./prod/app/config/firebase-credentials.json:/app/firebase-credentials.json
      - ./prod/app/files:/files
    ports:
      - "5000:80"
    depends_on:
      - "db"
    networks:
      - db
      - internet
networks:
  db:
    driver: bridge
    internal: true
  internet:
    driver: bridge

