// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Pronto_MIA.DataAccess.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class Deploymentplanadddepartment : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "DepartmentId",
                table: "DeploymentPlans",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_DeploymentPlans_DepartmentId",
                table: "DeploymentPlans",
                column: "DepartmentId");

            migrationBuilder.AddForeignKey(
                name: "FK_DeploymentPlans_Departments_DepartmentId",
                table: "DeploymentPlans",
                column: "DepartmentId",
                principalTable: "Departments",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_DeploymentPlans_Departments_DepartmentId",
                table: "DeploymentPlans");

            migrationBuilder.DropIndex(
                name: "IX_DeploymentPlans_DepartmentId",
                table: "DeploymentPlans");

            migrationBuilder.DropColumn(
                name: "DepartmentId",
                table: "DeploymentPlans");
        }
    }
}
