name: Server CI
on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: ls -la

      - name: Restore solution
        run: dotnet restore

      - name: Build with warnings as errors
        run: |
             dotnet build -c release -o ./app --no-restore -warnAsError | tee ./buildlog.txt
             grep '0 Error(s)' ./buildlog.txt
